
insert into cars (mark, model, engine, fuel, price, image) values ('Infiniti', 'FX', 'v8', 'hübriid(bensiin/elekter)', 72, '/nisl/duis/bibendum/felis/sed/interdum.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Kia', 'Sorento', 'v8', 'hübriid(bensiin/elekter)', 99, '/vitae/consectetuer/eget/rutrum/at/lorem.html');
insert into cars (mark, model, engine, fuel, price, image) values ('BMW', '5 Series', 'v6', 'gaas', 61, '/ut/tellus/nulla/ut/erat.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Mighty Max', 'v8', 'täiselekter', 25, '/vel/ipsum.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Land Rover', 'Range Rover Sport', 'v8', 'hübriid(bensiin/elekter)', 31, '/at/ipsum.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Dodge', 'Viper', 'v10', 'diisel', 13, '/pede/justo/lacinia/eget/tincidunt.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'MX-5', 'v6', 'gaas', 91, '/vestibulum.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'Passat', 'v8', 'hübriid(diisel/elekter)', 56, '/nulla.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Acura', 'Integra', 'v10', 'diisel', 26, '/in/hac/habitasse/platea.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'Mustang', 'v8', 'täiselekter', 89, '/gravida/nisi/at/nibh/in/hac/habitasse.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Pontiac', 'Solstice', 'v8', 'hübriid(bensiin/elekter)', 13, '/lectus/suspendisse/potenti.json');
insert into cars (mark, model, engine, fuel, price, image) values ('BMW', 'M5', 'v8', 'hübriid(diisel/elekter)', 42, '/nibh/in.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'Windstar', 'v10', 'hübriid(diisel/elekter)', 20, '/habitasse/platea/dictumst.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Camaro', 'v6', 'bensiin', 47, '/purus/sit/amet.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Buick', 'LeSabre', 'v6', 'täiselekter', 61, '/felis/fusce/posuere/felis/sed/lacus.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Buick', 'LeSabre', 'v6', 'gaas', 35, '/iaculis/justo/in/hac/habitasse/platea.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Subaru', 'Forester', 'v10', 'hübriid(diisel/elekter)', 10, '/velit/nec/nisi/vulputate/nonummy/maecenas.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'Land Cruiser', 'v8', 'gaas', 92, '/diam.html');
insert into cars (mark, model, engine, fuel, price, image) values ('BMW', '3 Series', 'v6', 'hübriid(bensiin/elekter)', 79, '/consectetuer/adipiscing/elit/proin/interdum/mauris/non.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Buick', 'Coachbuilder', 'v6', 'diisel', 48, '/pretium/quis/lectus.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Lexus', 'GX', 'v8', 'diisel', 20, '/aliquam/erat/volutpat/in/congue/etiam.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Saab', '900', 'v6', 'hübriid(diisel/elekter)', 13, '/metus/vitae/ipsum/aliquam/non/mauris/morbi.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'New Beetle', 'v8', 'bensiin', 49, '/risus/praesent/lectus/vestibulum/quam/sapien.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Monte Carlo', 'v6', 'täiselekter', 25, '/id.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Hyundai', 'Elantra', 'v8', 'hübriid(diisel/elekter)', 82, '/aliquam/sit/amet.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Chrysler', 'Fifth Ave', 'v6', 'bensiin', 42, '/justo/sollicitudin/ut/suscipit/a.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'GTI', 'v8', 'hübriid(bensiin/elekter)', 41, '/felis/sed.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'E-Class', 'v10', 'diisel', 44, '/odio/cras.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'RX-7', 'v6', 'bensiin', 75, '/mauris/enim/leo/rhoncus.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('GMC', 'Sierra 1500', 'v6', 'diisel', 14, '/ut.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('GMC', 'Canyon', 'v6', 'bensiin', 99, '/dolor/sit/amet/consectetuer/adipiscing/elit.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'F350', 'v10', 'hübriid(diisel/elekter)', 36, '/odio/condimentum/id/luctus/nec.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Eclipse', 'v8', 'hübriid(diisel/elekter)', 66, '/nullam.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercury', 'Cougar', 'v8', 'hübriid(diisel/elekter)', 16, '/proin/interdum.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'GTI', 'v8', 'täiselekter', 89, '/morbi/non/quam.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Pontiac', 'Chevette', 'v8', 'hübriid(bensiin/elekter)', 3, '/curabitur/in/libero/ut/massa/volutpat/convallis.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Corvette', 'v8', 'bensiin', 52, '/amet/lobortis/sapien/sapien/non.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Bentley', 'Continental GT', 'v6', 'diisel', 51, '/faucibus/orci/luctus/et.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Saab', '9-5', 'v10', 'täiselekter', 53, '/morbi/vel/lectus/in/quam/fringilla.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Lincoln', 'MKS', 'v8', 'täiselekter', 64, '/varius/integer/ac/leo/pellentesque.xml');